//! Hardware gamma-ramp dimming with a `WS_EX_LAYERED` overlay fallback.
//!
//! [`GammaDimmer`] adjusts the display's hardware gamma curve via
//! `SetDeviceGammaRamp`.  When that call fails (HDR displays, virtual
//! monitors, restricted driver permissions), it transparently falls back to
//! a fullscreen `WS_EX_LAYERED` overlay window that composites a
//! semi-transparent black layer over the desktop.
//!
//! The original gamma ramp (or overlay visibility) is restored automatically
//! when `GammaDimmer` is dropped.

/// Dims the display by adjusting the hardware gamma ramp, with an automatic
/// fallback to a fullscreen layered-overlay window.
///
/// # Usage
/// ```ignore
/// let dimmer = GammaDimmer::new();
/// dimmer.set_level(0.5); // 50 % dimming
/// dimmer.set_level(0.0); // restore
/// ```
pub struct GammaDimmer {
    #[cfg(windows)]
    inner: windows_impl::Inner,
}

impl GammaDimmer {
    /// Construct a `GammaDimmer`, selecting the best available strategy.
    pub fn new() -> Self {
        #[cfg(windows)]
        {
            GammaDimmer {
                inner: windows_impl::Inner::new(),
            }
        }
        #[cfg(not(windows))]
        {
            GammaDimmer {}
        }
    }

    /// Set the dimming level in `[0.0, 1.0]`.
    ///
    /// - `0.0` → no dimming (original ramp / overlay hidden)
    /// - `1.0` → maximum dimming (nearly black)
    pub fn set_level(&self, level: f32) {
        #[cfg(windows)]
        self.inner.set_level(level);
        #[cfg(not(windows))]
        let _ = level;
    }
}

impl Default for GammaDimmer {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Windows implementation
// ---------------------------------------------------------------------------

#[cfg(windows)]
mod windows_impl {
    use std::sync::atomic::{AtomicBool, AtomicU32, Ordering};
    use std::sync::Arc;
    use std::{mem, thread, time::Duration};

    use tracing::{info, warn};

    use windows::Win32::Foundation::{COLORREF, HINSTANCE, HWND, LPARAM, LRESULT, WPARAM};
    use windows::Win32::Graphics::Gdi::HBRUSH;
    use windows::Win32::System::LibraryLoader::GetModuleHandleW;
    use windows::Win32::UI::WindowsAndMessaging::{
        CreateWindowExW, DefWindowProcW, DestroyWindow, DispatchMessageW, GetSystemMetrics,
        PeekMessageW, RegisterClassExW, SetLayeredWindowAttributes, ShowWindow, TranslateMessage,
        LWA_ALPHA, MSG, PM_REMOVE, SM_CXSCREEN, SM_CYSCREEN, SW_HIDE, SW_SHOWNOACTIVATE,
        WNDCLASSEXW, WS_EX_LAYERED, WS_EX_TOPMOST, WS_EX_TRANSPARENT, WS_POPUP,
    };
    use windows::core::PCWSTR;

    // -----------------------------------------------------------------------
    // Raw Win32 declarations
    //
    // GetDeviceGammaRamp / SetDeviceGammaRamp are legacy GDI functions not
    // always included in the windows-rs autogenerated bindings.  Use raw
    // extern declarations to guarantee availability.
    // -----------------------------------------------------------------------

    #[link(name = "user32")]
    extern "system" {
        fn GetDC(hwnd: *mut core::ffi::c_void) -> *mut core::ffi::c_void;
        fn ReleaseDC(hwnd: *mut core::ffi::c_void, hdc: *mut core::ffi::c_void) -> i32;
    }

    #[link(name = "gdi32")]
    extern "system" {
        fn GetDeviceGammaRamp(
            hdc: *mut core::ffi::c_void,
            ramp: *mut core::ffi::c_void,
        ) -> i32;
        fn SetDeviceGammaRamp(
            hdc: *mut core::ffi::c_void,
            ramp: *const core::ffi::c_void,
        ) -> i32;
        /// Returns a stock GDI object handle (not owned; do not delete).
        fn GetStockObject(fnObject: i32) -> *mut core::ffi::c_void;
    }

    /// Stock object index for a solid black brush.
    const BLACK_BRUSH_IDX: i32 = 4;

    // -----------------------------------------------------------------------
    // Gamma-ramp helpers
    // -----------------------------------------------------------------------

    /// Flat buffer: R[0..256], G[256..512], B[512..768] — 768 × u16.
    type GammaRamp = [u16; 768];

    /// Linear (identity) ramp: entry[i] = i × 257.
    fn identity_ramp() -> GammaRamp {
        let mut ramp = [0u16; 768];
        for ch in 0..3usize {
            for i in 0..256usize {
                ramp[ch * 256 + i] = (i as u16).saturating_mul(257);
            }
        }
        ramp
    }

    /// Scale `saved` ramp by `(1 − level)` to produce a darker curve.
    fn scaled_ramp(saved: &GammaRamp, level: f32) -> GammaRamp {
        let factor = (1.0_f32 - level.clamp(0.0, 1.0)) as f64;
        let mut out = [0u16; 768];
        for (v, &s) in out.iter_mut().zip(saved.iter()) {
            *v = (s as f64 * factor) as u16;
        }
        out
    }

    // -----------------------------------------------------------------------
    // Primary strategy: SetDeviceGammaRamp
    // -----------------------------------------------------------------------

    struct GammaDimmerInner {
        /// Raw HDC for the primary display (screen DC).
        hdc: *mut core::ffi::c_void,
        saved: GammaRamp,
    }

    // SAFETY: the screen DC returned by GetDC(NULL) is valid from any thread.
    // Only the pipeline thread calls set_level, so no concurrent writes occur.
    unsafe impl Send for GammaDimmerInner {}

    impl GammaDimmerInner {
        fn try_new() -> Option<Self> {
            unsafe {
                let hdc = GetDC(core::ptr::null_mut());
                if hdc.is_null() {
                    warn!("GammaDimmer: GetDC returned null");
                    return None;
                }
                let mut saved: GammaRamp = identity_ramp();
                let ok = GetDeviceGammaRamp(hdc, saved.as_mut_ptr().cast());
                if ok == 0 {
                    warn!(
                        "GammaDimmer: GetDeviceGammaRamp failed — trying overlay fallback"
                    );
                    ReleaseDC(core::ptr::null_mut(), hdc);
                    return None;
                }
                info!("GammaDimmer: using SetDeviceGammaRamp (primary)");
                Some(GammaDimmerInner { hdc, saved })
            }
        }

        fn set_level(&self, level: f32) {
            let ramp = scaled_ramp(&self.saved, level);
            unsafe {
                SetDeviceGammaRamp(self.hdc, ramp.as_ptr().cast());
            }
        }
    }

    impl Drop for GammaDimmerInner {
        fn drop(&mut self) {
            unsafe {
                // Restore original ramp before releasing the DC.
                SetDeviceGammaRamp(self.hdc, self.saved.as_ptr().cast());
                ReleaseDC(core::ptr::null_mut(), self.hdc);
            }
        }
    }

    // -----------------------------------------------------------------------
    // Fallback strategy: WS_EX_LAYERED fullscreen overlay
    // -----------------------------------------------------------------------

    struct OverlayDimmer {
        /// Desired alpha: 0 = transparent, 255 = opaque black.
        alpha: Arc<AtomicU32>,
        shutdown: Arc<AtomicBool>,
        thread: Option<thread::JoinHandle<()>>,
    }

    impl OverlayDimmer {
        fn new() -> Self {
            let alpha = Arc::new(AtomicU32::new(0));
            let shutdown = Arc::new(AtomicBool::new(false));

            let alpha_clone = Arc::clone(&alpha);
            let shutdown_clone = Arc::clone(&shutdown);

            let thread = thread::Builder::new()
                .name("flashsafe-overlay".into())
                .spawn(move || overlay_thread(alpha_clone, shutdown_clone))
                .ok();

            info!("GammaDimmer: using WS_EX_LAYERED overlay (fallback)");
            OverlayDimmer { alpha, shutdown, thread }
        }

        fn set_level(&self, level: f32) {
            let alpha = (level.clamp(0.0, 1.0) * 255.0).round() as u32;
            self.alpha.store(alpha, Ordering::Relaxed);
        }
    }

    impl Drop for OverlayDimmer {
        fn drop(&mut self) {
            self.shutdown.store(true, Ordering::Relaxed);
            if let Some(t) = self.thread.take() {
                let _ = t.join();
            }
        }
    }

    unsafe extern "system" fn overlay_wndproc(
        hwnd: HWND,
        msg: u32,
        wparam: WPARAM,
        lparam: LPARAM,
    ) -> LRESULT {
        DefWindowProcW(hwnd, msg, wparam, lparam)
    }

    fn overlay_thread(alpha: Arc<AtomicU32>, shutdown: Arc<AtomicBool>) {
        unsafe {
            // Derive HINSTANCE from the executable module.
            let hinstance = match GetModuleHandleW(None) {
                Ok(h) => HINSTANCE(h.0),
                Err(_) => HINSTANCE(core::ptr::null_mut()),
            };

            let class_name: Vec<u16> = "FlashSafeOverlay\0".encode_utf16().collect();

            // Register the window class; ignore "already registered" errors.
            let black_brush = HBRUSH(GetStockObject(BLACK_BRUSH_IDX));
            let wc = WNDCLASSEXW {
                cbSize: mem::size_of::<WNDCLASSEXW>() as u32,
                lpszClassName: PCWSTR(class_name.as_ptr()),
                lpfnWndProc: Some(overlay_wndproc),
                hInstance: hinstance,
                hbrBackground: black_brush,
                ..Default::default()
            };
            let _ = RegisterClassExW(&wc);

            let screen_w = GetSystemMetrics(SM_CXSCREEN);
            let screen_h = GetSystemMetrics(SM_CYSCREEN);

            let hwnd = match CreateWindowExW(
                WS_EX_LAYERED | WS_EX_TOPMOST | WS_EX_TRANSPARENT,
                PCWSTR(class_name.as_ptr()),
                PCWSTR::null(),
                WS_POPUP,
                0, 0,
                screen_w, screen_h,
                None, None,
                hinstance,
                None,
            ) {
                Ok(h) => h,
                Err(e) => {
                    warn!("GammaDimmer overlay: CreateWindowExW failed: {:?}", e);
                    return;
                }
            };

            // Initialize fully transparent so nothing is visible yet.
            let _ = SetLayeredWindowAttributes(hwnd, COLORREF(0), 0, LWA_ALPHA);

            let mut prev_alpha = u32::MAX; // force first update on entry

            loop {
                if shutdown.load(Ordering::Relaxed) {
                    break;
                }

                let a = alpha.load(Ordering::Relaxed);
                if a != prev_alpha {
                    prev_alpha = a;
                    let _ = SetLayeredWindowAttributes(
                        hwnd,
                        COLORREF(0),
                        a.min(255) as u8,
                        LWA_ALPHA,
                    );
                    if a == 0 {
                        let _ = ShowWindow(hwnd, SW_HIDE);
                    } else {
                        let _ = ShowWindow(hwnd, SW_SHOWNOACTIVATE);
                    }
                }

                // Drain pending messages so the window stays responsive.
                let mut msg = MSG::default();
                while PeekMessageW(&mut msg, hwnd, 0, 0, PM_REMOVE).as_bool() {
                    let _ = TranslateMessage(&msg);
                    DispatchMessageW(&msg);
                }

                // ~250 Hz poll — fast enough for smooth fades, cheap on CPU.
                thread::sleep(Duration::from_millis(4));
            }

            let _ = DestroyWindow(hwnd);
        }
    }

    // -----------------------------------------------------------------------
    // Inner enum — selects the strategy at construction time
    // -----------------------------------------------------------------------

    pub(super) enum Inner {
        Gamma(#[allow(private_interfaces)] GammaDimmerInner),
        Overlay(#[allow(private_interfaces)] OverlayDimmer),
    }

    impl Inner {
        pub(super) fn new() -> Self {
            match GammaDimmerInner::try_new() {
                Some(g) => Inner::Gamma(g),
                None => Inner::Overlay(OverlayDimmer::new()),
            }
        }

        pub(super) fn set_level(&self, level: f32) {
            match self {
                Inner::Gamma(g) => g.set_level(level),
                Inner::Overlay(o) => o.set_level(level),
            }
        }
    }
}
